### ISSUE TITLE
how to build ePassportReader?

### ISSUE THREAD

**Issue by coffeenkfc** [alximw/ePassportReader#1]
Hi, I'm an newb and was recommended to look at your project to learn how to use JMRTD. I'm using Android Studio. It doesn't seem to import right; what tools/environment should I be using to build the project? Thanks!

**Comment by alximw** [comment]
Hi!

I recommend you to use Eclipse instead of Android Studio for compilling
this project.

Cheers!

**Comment by coffeenkfc** [comment]
Thank you very much alximw, I was able to build and run inside eclipse ADT. :)
